import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { transform, build as esbuildBundle } from "esbuild";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const dist = path.join(root, "dist");
const assets = path.join(dist, "assets");

const SITE_NAME = "RAISA Studio";
const SITE_TITLE = "RAISA Studio - Graphic Design x Software Development";
const SITE_DESCRIPTION = "A split-discipline portfolio for graphic design, branding, websites, web apps, and production-ready digital work.";
const THEME_COLOR = "#0B1B3A";

function parseBoolean(value, fallback = false) {
  if (value == null || value === "") return fallback;
  return ["1", "true", "yes", "on"].includes(String(value).toLowerCase());
}

function cleanSiteUrl(value) {
  if (!value) return "";
  return String(value).trim().replace(/\/+$/, "");
}

function escapeAttr(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function toJs(value) {
  return JSON.stringify(value, null, 2)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

async function loadDotEnv(filePath) {
  let source = "";
  try {
    source = await readFile(filePath, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return;
    throw error;
  }

  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match || process.env[match[1]] != null) continue;

    let value = match[2].trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    process.env[match[1]] = value;
  }
}

await loadDotEnv(path.join(root, ".env"));

const siteUrl = cleanSiteUrl(process.env.PORTFOLIO_SITE_URL);
const adminPasscode = String(process.env.PORTFOLIO_ADMIN_PASSCODE || "").trim();
const adminEnabled = parseBoolean(process.env.PORTFOLIO_ENABLE_ADMIN, Boolean(adminPasscode));
const tweaksEnabled = parseBoolean(process.env.PORTFOLIO_ENABLE_TWEAKS, false);
const noIndex = parseBoolean(process.env.PORTFOLIO_NO_INDEX, false);
// Supabase — supports both VITE_ prefix (Vite projects) and plain names
const supabaseUrl = String(process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || "").trim();
const supabaseAnonKey = String(process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || "").trim();
const supabaseEnabled = Boolean(supabaseUrl && supabaseAnonKey);

if (adminEnabled && (!adminPasscode || adminPasscode === "change-me")) {
  throw new Error("Set PORTFOLIO_ADMIN_PASSCODE to a non-default value before building with admin enabled.");
}

const jsxFiles = [
  "tweaks-panel.jsx",
  "icons.jsx",
  "shared.jsx",
  "cursor.jsx",
  "hero.jsx",
  "graphic-page.jsx",
  "webdev-page.jsx",
  "case-sheet.jsx",
  "content.jsx",
  "supabase-client.jsx",
  "admin-panel.jsx",
  "app.jsx",
];

await rm(dist, { recursive: true, force: true });
await mkdir(assets, { recursive: true });
await copyFile(path.join(root, "styles.css"), path.join(assets, "styles.css"));

let bundle = "/* Generated by npm run build. Do not edit dist files directly. */\n";

for (const file of jsxFiles) {
  const source = await readFile(path.join(root, file), "utf8");
  const result = await transform(source, {
    loader: "jsx",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    target: "es2018",
    minify: true,
    legalComments: "none",
  });

  bundle += `\n;(() => {\n${result.code}\n})();\n`;
}

await writeFile(path.join(assets, "app.js"), bundle, "utf8");

// Bundle framer-motion with React globals mapped to window.React / window.ReactDOM
const reactGlobalsPlugin = {
  name: "react-globals",
  setup(build) {
    const shims = new Map([
      ["react",             "module.exports = window.React;"],
      ["react-dom",         "module.exports = window.ReactDOM;"],
      ["react/jsx-runtime", "module.exports = { createElement: window.React.createElement, Fragment: window.React.Fragment, jsx: window.React.createElement, jsxs: window.React.createElement };"],
      ["react-dom/client",  "module.exports = window.ReactDOM;"],
    ]);
    build.onResolve({ filter: /^react/ }, (args) => {
      if (shims.has(args.path)) return { path: args.path, namespace: "react-shim" };
    });
    build.onLoad({ filter: /.*/, namespace: "react-shim" }, (args) => ({
      contents: shims.get(args.path) || "module.exports = {};",
      loader: "js",
    }));
  },
};

await esbuildBundle({
  entryPoints: [path.join(root, "framer-motion-entry.js")],
  bundle: true,
  outfile: path.join(assets, "framer-motion.js"),
  format: "iife",
  globalName: "FramerMotion",
  platform: "browser",
  define: { "process.env.NODE_ENV": '"production"' },
  minify: true,
  plugins: [reactGlobalsPlugin],
  logLevel: "silent",
});

await writeFile(path.join(assets, "config.js"), `window.PortfolioConfig = ${toJs({
  adminEnabled,
  adminPasscode: adminEnabled ? adminPasscode : "",
  tweaksEnabled,
  siteUrl,
  supabaseUrl,
  supabaseAnonKey,
  buildTime: new Date().toISOString(),
})};
window.PORTFOLIO_ADMIN_PASSCODE = window.PortfolioConfig.adminPasscode;
window.PORTFOLIO_ENABLE_ADMIN = window.PortfolioConfig.adminEnabled;
window.PORTFOLIO_ENABLE_TWEAKS = window.PortfolioConfig.tweaksEnabled;
`, "utf8");

const canonicalTags = siteUrl ? `
<link rel="canonical" href="${escapeAttr(siteUrl)}/" />
<meta property="og:url" content="${escapeAttr(siteUrl)}/" />` : "";
const robotsMeta = noIndex ? `<meta name="robots" content="noindex, nofollow" />` : "";

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="${escapeAttr(SITE_DESCRIPTION)}" />
${robotsMeta}
<meta name="theme-color" content="${THEME_COLOR}" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="${escapeAttr(SITE_NAME)}" />
<meta property="og:title" content="${escapeAttr(SITE_TITLE)}" />
<meta property="og:description" content="${escapeAttr(SITE_DESCRIPTION)}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${escapeAttr(SITE_TITLE)}" />
<meta name="twitter:description" content="${escapeAttr(SITE_DESCRIPTION)}" />${canonicalTags}
<title>${escapeAttr(SITE_TITLE)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Manrope:wght@300;400;500;600;700&family=Fraunces:ital,opsz,wght@0,9..144,400;1,9..144,400;1,9..144,500&family=JetBrains+Mono:wght@400;500&family=Archivo:wght@500;700;800&family=Inter+Tight:wght@400;500;600&family=DM+Sans:wght@400;500;700&family=IBM+Plex+Sans:wght@400;500;600&family=Bricolage+Grotesque:wght@500;700;800&family=Instrument+Serif&display=swap" rel="stylesheet">
<link rel="icon" href="favicon.svg" type="image/svg+xml" />
<link rel="manifest" href="site.webmanifest" />
<link rel="stylesheet" href="assets/styles.css" />
</head>
<body>
<div id="root"></div>
<noscript>This portfolio needs JavaScript enabled to run the interactive split-screen experience.</noscript>
<script src="assets/config.js"></script>
<script src="https://unpkg.com/react@18.3.1/umd/react.production.min.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js" crossorigin="anonymous"></script>
${supabaseEnabled ? '<script src="https://unpkg.com/@supabase/supabase-js@2/dist/umd/supabase.js" crossorigin="anonymous"></script>' : ""}
<script src="https://unpkg.com/gsap@3.12.5/dist/gsap.min.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/three@0.160.1/build/three.min.js" crossorigin="anonymous"></script>
<script src="assets/framer-motion.js"></script>
<script src="assets/app.js"></script>
</body>
</html>
`;

await writeFile(path.join(dist, "index.html"), html, "utf8");
await writeFile(path.join(dist, "404.html"), html, "utf8");

await writeFile(path.join(dist, "robots.txt"), noIndex
  ? "User-agent: *\nDisallow: /\n"
  : `User-agent: *\nAllow: /\n${siteUrl ? `Sitemap: ${siteUrl}/sitemap.xml\n` : ""}`, "utf8");

if (siteUrl) {
  await writeFile(path.join(dist, "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${escapeAttr(siteUrl)}/</loc>
    <lastmod>${new Date().toISOString().slice(0, 10)}</lastmod>
    <priority>1.0</priority>
  </url>
</urlset>
`, "utf8");
}

await writeFile(path.join(dist, "site.webmanifest"), JSON.stringify({
  name: SITE_NAME,
  short_name: "RAISA",
  start_url: ".",
  display: "standalone",
  background_color: "#FAF7F1",
  theme_color: THEME_COLOR,
  icons: [
    {
      src: "favicon.svg",
      sizes: "any",
      type: "image/svg+xml",
    },
  ],
}, null, 2), "utf8");

await writeFile(path.join(dist, "favicon.svg"), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="14" fill="#E63946"/>
  <path d="M18 16h9l5.3 22.5L37.8 16H47L37.6 48H27.1L18 16Z" fill="#fff"/>
</svg>
`, "utf8");

await writeFile(path.join(dist, "_redirects"), "/* /index.html 200\n", "utf8");

const supabaseCspSuffix = supabaseEnabled ? " https://*.supabase.co" : "";
await writeFile(path.join(dist, "_headers"), `/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Permissions-Policy: camera=(), microphone=(), geolocation=()
  Content-Security-Policy: default-src 'self'; script-src 'self' https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data: blob:${supabaseCspSuffix}; connect-src 'self' https://api.github.com${supabaseCspSuffix}; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self' mailto:

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/index.html
  Cache-Control: no-cache
`, "utf8");

console.log(`Built ${path.relative(root, dist)} with ${jsxFiles.length} JSX files.`);
console.log(`Admin panel: ${adminEnabled ? "enabled" : "disabled"}${siteUrl ? ` | URL: ${siteUrl}` : ""}`);
console.log(`Supabase backend: ${supabaseEnabled ? `enabled (${supabaseUrl})` : "disabled (localStorage mode)"}`);
